// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: homeassistant

#ifndef _HOMEASSISTANT_UI_H
#define _HOMEASSISTANT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui____initial_actions0;

extern int led_flag_Lock;
extern int led_flag;

LV_IMG_DECLARE(ui_img_1797371272);    // assets/lightbulb-outline_40.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
